manifest:
    remotes:
        - name: zmkfirmware
          url-base: https://github.com/zmkfirmware
        - name: hf02
          url-base: https://github.com/hf02
        # Additional modules containing boards/shields/custom code can be listed here as well
        # See https://docs.zephyrproject.org/3.2.0/develop/west/manifest.html#projects
    projects:
        - name: zmk
          remote: zmkfirmware
          revision: main
          import: app/west.yml
        - name: nice-view-gem #new entry
          remote: hf02 #new entry
          revision: main #new entry
        - name: nice-view-turtle #new entry
          remote: hf02 #new entry
          revision: main #new entry
    self:
        path: config
